(() => {
  'use strict';
  const $ = (s) => document.querySelector(s);
  const screens = ['#home','#connect-screen','#settings-screen','#files-screen'];
  const DB_NAME = 'echo-remote-files';
  let peer = null, dataConn = null, mediaCall = null, activePc = null, toastTimer = 0, wakeLock = null;
  let receivedFiles = new Map(), pointerDown = false, transferState = null, audioContext = null, audioEnabled = false, audioNextTime = 0, audioSources = new Set();
  const pcStore = {
    get all(){ try{return JSON.parse(localStorage.getItem('echo-remote-pcs')||'[]')}catch{return[]} },
    save(list){localStorage.setItem('echo-remote-pcs',JSON.stringify(list));renderPcs()}
  };
  const settings = {
    get(key,fallback){return localStorage.getItem('echo-remote-'+key) ?? fallback},
    set(key,value){localStorage.setItem('echo-remote-'+key,String(value))}
  };
  function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),2800)}
  function hideScreens(){screens.forEach(s=>$(s).classList.add('hidden'));$('#viewer-screen').classList.add('hidden')}
  function showScreen(selector){hideScreens();$(selector).classList.remove('hidden');if(selector==='#connect-screen')renderPcs();if(selector==='#files-screen')renderFiles()}
  function updateHomeCount(){$('#pc-count').textContent=`登録済みPC ${pcStore.all.length}台`}
  function safeText(value){return String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
  function renderPcs(){const list=$('#pc-list');list.replaceChildren();const pcs=pcStore.all;$('#pc-empty').classList.toggle('hidden',pcs.length>0);updateHomeCount();for(const pc of pcs){const row=document.createElement('div');row.className='pc-card';row.innerHTML=`<span class="pc-glyph">▣</span><span class="card-copy"><strong>${safeText(pc.name)}</strong><small>PeerJS · ${safeText(pc.peerId)}</small></span><button class="card-action delete-pc" title="PCを削除" aria-label="PCを削除">×</button>`;row.querySelector('.delete-pc').addEventListener('click',e=>{e.stopPropagation();if(activePc?.id===pc.id)disconnect('登録したPCを削除しました');pcStore.save(pcStore.all.filter(p=>p.id!==pc.id));toast('PC登録を削除しました')});row.addEventListener('click',()=>connectPc(pc));list.append(row)}}
  async function openDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('files'))db.createObjectStore('files',{keyPath:'id'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
  async function dbAll(){const db=await openDb();return new Promise((resolve,reject)=>{const q=db.transaction('files','readonly').objectStore('files').getAll();q.onsuccess=()=>resolve(q.result.sort((a,b)=>b.savedAt-a.savedAt));q.onerror=()=>reject(q.error)})}
  async function dbPut(file){const db=await openDb();return new Promise((resolve,reject)=>{const q=db.transaction('files','readwrite').objectStore('files').put(file);q.onsuccess=()=>resolve();q.onerror=()=>reject(q.error)})}
  async function dbDelete(id){const db=await openDb();return new Promise((resolve,reject)=>{const q=db.transaction('files','readwrite').objectStore('files').delete(id);q.onsuccess=()=>resolve();q.onerror=()=>reject(q.error)})}
  function prettySize(n){if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(0)} KB`;if(n<1073741824)return `${(n/1048576).toFixed(1)} MB`;return `${(n/1073741824).toFixed(2)} GB`}
  async function renderFiles(){const list=$('#file-list');list.replaceChildren();try{const items=await dbAll();$('#files-empty').classList.toggle('hidden',items.length>0);for(const f of items){const row=document.createElement('div');row.className='file-card';const ext=(f.name.split('.').pop()||'').toLowerCase();row.innerHTML=`<span class="file-glyph">${['jpg','jpeg','png','gif','webp'].includes(ext)?'▧':['mp4','webm','mov'].includes(ext)?'▷':['mp3','wav','m4a','ogg'].includes(ext)?'♫':ext==='pdf'?'▤':'▣'}</span><span class="card-copy"><strong>${safeText(f.name)}</strong><small>${prettySize(f.size)} · ${new Date(f.savedAt).toLocaleString()}</small></span><button class="card-action" aria-label="閲覧">›</button><button class="card-action delete-pc" aria-label="削除">×</button>`;row.querySelector('.card-copy').addEventListener('click',()=>openFile(f));row.querySelectorAll('.card-action')[0].addEventListener('click',()=>openFile(f));row.querySelector('.delete-pc').addEventListener('click',async()=>{await dbDelete(f.id);renderFiles();toast('ファイルを削除しました')});list.append(row)}}catch(e){toast('ファイル一覧を開けませんでした')}}
  async function openFile(item){const blob=item.blob instanceof Blob?item.blob:new Blob([item.blob],{type:item.type||'application/octet-stream'});const url=URL.createObjectURL(blob);const body=$('#preview-body');body.replaceChildren();$('#preview-title').textContent=item.name;const ext=(item.name.split('.').pop()||'').toLowerCase();if(['png','jpg','jpeg','gif','webp','bmp'].includes(ext)){const el=document.createElement('img');el.src=url;el.alt=item.name;body.append(el)}else if(['mp4','webm','mov','m4v'].includes(ext)){const el=document.createElement('video');el.src=url;el.controls=true;el.playsInline=true;body.append(el)}else if(['mp3','wav','m4a','ogg','aac','flac'].includes(ext)){const el=document.createElement('audio');el.src=url;el.controls=true;body.append(el)}else if(ext==='pdf'){const el=document.createElement('iframe');el.src=url;el.title=item.name;body.append(el)}else if(['txt','md','csv','log','json','xml'].includes(ext)){const pre=document.createElement('pre');try{pre.textContent=await blob.text()}catch{pre.textContent='このファイルを読み込めません'}body.append(pre)}else{const note=document.createElement('div');note.className='unsupported';note.textContent='この形式は画面内プレビューに対応していません。ファイルマネージャーから削除するか、ダウンロード後に開いてください。';body.append(note);const link=document.createElement('a');link.href=url;link.download=item.name;link.className='pill-button';link.textContent='ダウンロード';link.style.marginTop='14px';body.append(link)}$('#file-preview').showModal();$('#file-preview').dataset.url=url}
  function setPeerStatus(text,good=false){const status=$('#peer-status');if(status)status.textContent=text;const dot=$('.status-dot');if(dot)dot.style.background=good?'#68dba4':'#67caee'}
  function initPeer(){if(typeof Peer==='undefined'){setPeerStatus('PeerJSライブラリを読み込めません');return}try{peer=new Peer(undefined,{debug:0});peer.on('open',id=>setPeerStatus(`PeerJS ready · ${id.slice(0,8)}`,true));peer.on('error',e=>{setPeerStatus('PeerJS接続エラー');if(e.type!=='peer-unavailable')toast(`PeerJS: ${e.type||e.message}`)});peer.on('disconnected',()=>setPeerStatus('PeerJS signaling切断'));peer.on('close',()=>setPeerStatus('PeerJS終了'))}catch(e){setPeerStatus('PeerJSを開始できません')}}
  async function connectPc(pc){if(!peer||!peer.open){toast('PeerJS signalingの起動を待っています');return}if(location.protocol==='file:'){toast('file://ではなくHTTPSで開いてください');return}disconnect('',false);activePc=pc;$('#viewer-device').textContent=pc.name;$('#video-message').textContent='PCに接続しています…';$('#live-indicator').classList.remove('connected');$('#keyboard-panel').classList.add('hidden');hideScreens();$('#viewer-screen').classList.remove('hidden');setWakeLock();try{dataConn=peer.connect(pc.peerId,{reliable:true,serialization:'json',metadata:{client:'echo-show'}});let authed=false;dataConn.on('open',()=>{dataConn.send({type:'auth',password:pc.password});$('#video-message').textContent='接続を認証しています…'});dataConn.on('data',data=>{if(!data||typeof data!=='object')return;if(data.type==='auth-ok'){authed=true;$('#video-message').textContent='PC画面を接続しています…';toast('PCに接続しました');sendSetting();startCall(pc)}else if(data.type==='auth-failed'){toast('パスワードが違います');disconnect('',false)}else if(data.type==='frame-info'){}else if(data.type==='audio-state'){setAudioState(!!data.enabled,data.message||'')}else if(data.type==='audio-data'){playAudioChunk(data)}else if(data.type==='file-start'){if(data.size>536870912){sendMessage({type:'file-reject',id:data.id});toast('1ファイル512 MiBまでです');return}receivedFiles.set(data.id,{name:data.name,size:data.size,type:data.mime||'application/octet-stream',chunks:[],received:0});toast(`${data.name} を受信中…`)}else if(data.type==='file-chunk'){const st=receivedFiles.get(data.id);if(st){st.chunks[data.index]=base64ToBytes(data.data);st.received+=st.chunks[data.index].length;sendMessage({type:'file-chunk-ack',id:data.id,index:data.index});const p=st.size?Math.min(100,Math.round(st.received/st.size*100)):100;$('#video-message').textContent=`ファイル受信中 ${p}% · ${st.name}`;if(st.received>=st.size)finishFile(data.id,st)}}else if(data.type==='file-end'){const st=receivedFiles.get(data.id);if(st&&st.received>=st.size)finishFile(data.id,st)}else if(data.type==='file-error'){toast(data.message||'ファイルを取得できませんでした')}else if(data.type==='notice'){toast(data.message)}});dataConn.on('close',()=>{setAudioState(false);if(authed)toast('PCとのデータ接続が終了しました')});dataConn.on('error',()=>toast('データ接続に失敗しました'))}catch(e){toast('PCへ接続できません');disconnect('',false)}}
  function startCall(pc){if(!peer||!peer.open)return;try{const dummy=document.createElement('canvas');dummy.width=2;dummy.height=2;const ctx=dummy.getContext('2d');ctx.fillStyle='#000';ctx.fillRect(0,0,2,2);const silentStream=dummy.captureStream(1);mediaCall=peer.call(pc.peerId,silentStream,{metadata:{client:'echo-show'}});if(!mediaCall){toast('映像呼び出しを開始できませんでした');return}mediaCall.on('stream',stream=>{const v=$('#remote-video');v.srcObject=stream;v.play().catch(()=>{});$('#video-message').classList.add('hidden');$('#live-indicator').classList.add('connected')});mediaCall.on('close',()=>{if($('#viewer-screen').classList.contains('hidden'))return;$('#video-message').textContent='映像接続が終了しました';$('#video-message').classList.remove('hidden');$('#live-indicator').classList.remove('connected')});mediaCall.on('error',()=>toast('映像接続に失敗しました'))}catch(e){toast('このブラウザでWebRTC通話を開始できません')}}
  function sendSetting(){if(!dataConn?.open)return;dataConn.send({type:'settings',mode:$('#display-mode').value,fit:$('#fit-screen').checked,resolution:Number($('#stream-resolution').value)})}
  function sendMessage(message){if(dataConn?.open)dataConn.send(message);else toast('PCに接続されていません')}
  function disconnect(message='PCから切断しました',showHome=true){if(audioEnabled&&dataConn?.open)dataConn.send({type:'audio',enabled:false});setAudioState(false);$('#viewer-screen').classList.remove('toolbar-hidden');if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});if(mediaCall){try{mediaCall.close()}catch{}mediaCall=null}if(dataConn){try{dataConn.close()}catch{}dataConn=null}$('#remote-video').srcObject=null;$('#live-indicator').classList.remove('connected');activePc=null;pointerDown=false;if(wakeLock){wakeLock.release().catch(()=>{});wakeLock=null}if(showHome)showScreen('#home');if(message)toast(message)}
  function base64ToBytes(str){const bin=atob(str);const out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
  async function finishFile(id,st){if(!receivedFiles.has(id))return;receivedFiles.delete(id);const blob=new Blob(st.chunks,{type:st.type});try{await dbPut({id:`${Date.now()}-${crypto.randomUUID()}`,name:st.name,size:blob.size,type:st.type,blob,savedAt:Date.now()});toast(`${st.name} をこの端末に保存しました`);$('#video-message').classList.add('hidden');if(!$('#files-screen').classList.contains('hidden'))renderFiles()}catch{toast('IndexedDBへの保存に失敗しました')}}
  function requestFiles(){sendMessage({type:'request-files'});toast('PC側で送信するファイルを選んでください')}
  function videoPoint(e){const v=$('#remote-video');const r=v.getBoundingClientRect();const vw=v.videoWidth||r.width,vh=v.videoHeight||r.height;const scale=Math.min(r.width/vw,r.height/vh);const w=vw*scale,h=vh*scale;const left=r.left+(r.width-w)/2,top=r.top+(r.height-h)/2;return{x:Math.max(0,Math.min(1,(e.clientX-left)/w)),y:Math.max(0,Math.min(1,(e.clientY-top)/h))}}
  function bindVideoInput(){const v=$('#remote-video');v.addEventListener('contextmenu',e=>e.preventDefault());v.addEventListener('pointerdown',e=>{if(!dataConn?.open)return;e.preventDefault();v.setPointerCapture(e.pointerId);pointerDown=true;const p=videoPoint(e);sendMessage({type:'pointer',action:'down',x:p.x,y:p.y,button:e.button||0})});v.addEventListener('pointermove',e=>{if(!pointerDown)return;const p=videoPoint(e);sendMessage({type:'pointer',action:'move',x:p.x,y:p.y})});const up=e=>{if(!pointerDown)return;pointerDown=false;const p=videoPoint(e);sendMessage({type:'pointer',action:'up',x:p.x,y:p.y,button:e.button||0})};v.addEventListener('pointerup',up);v.addEventListener('pointercancel',up)}
  $('#add-pc').addEventListener('click',()=>$('#add-dialog').showModal());$('#connect-add').addEventListener('click',()=>$('#add-dialog').showModal());
  $('#add-form').addEventListener('submit',e=>{e.preventDefault();const name=$('#pc-name').value.trim(),peerId=$('#peer-code').value.trim(),password=$('#peer-password').value;if(!name||!peerId||!password)return;const all=pcStore.all.filter(p=>p.peerId!==peerId);all.push({id:crypto.randomUUID(),name,peerId,password});pcStore.save(all);$('#add-dialog').close();e.target.reset();toast('PCを登録しました')});
  $('#open-connect').addEventListener('click',()=>showScreen('#connect-screen'));$('#open-settings').addEventListener('click',()=>showScreen('#settings-screen'));$('#open-files').addEventListener('click',()=>showScreen('#files-screen'));document.querySelectorAll('[data-home]').forEach(b=>b.addEventListener('click',()=>showScreen('#home')));
  $('#display-mode').value=settings.get('display-mode','clone');const dpiOptions=['75','90','100','110','125','150'];const savedDpi=settings.get('app-dpi','100');$('#app-dpi').value=dpiOptions.includes(savedDpi)?savedDpi:'100';applyAppDpi();$('#app-dpi').addEventListener('change',()=>{settings.set('app-dpi',$('#app-dpi').value);applyAppDpi()});const savedResolution=settings.get('stream-resolution','1280');$('#stream-resolution').value=['640','960','1280','1600','1920','2560','3840'].includes(savedResolution)?savedResolution:'1280';$('#stream-resolution').addEventListener('change',()=>{settings.set('stream-resolution',$('#stream-resolution').value);sendSetting()});$('#fit-screen').checked=settings.get('fit-screen','true')==='true';$('#keep-awake').checked=settings.get('keep-awake','false')==='true';$('#display-mode').addEventListener('change',()=>{settings.set('display-mode',$('#display-mode').value);sendSetting()});$('#fit-screen').addEventListener('change',()=>{settings.set('fit-screen',$('#fit-screen').checked);sendSetting();$('#remote-video').style.objectFit=$('#fit-screen').checked?'contain':'cover'});$('#remote-video').style.objectFit=$('#fit-screen').checked?'contain':'cover';$('#keep-awake').addEventListener('change',()=>{settings.set('keep-awake',$('#keep-awake').checked);setWakeLock()});
  $('#exit-viewer').addEventListener('click',()=>disconnect());$('#disconnect').addEventListener('click',()=>disconnect());$('#viewer-files').addEventListener('click',requestFiles);$('#fullscreen').addEventListener('click',toggleFullscreen);$('#toolbar-toggle').addEventListener('click',hideToolbar);$('#show-toolbar').addEventListener('click',showToolbar);$('#audio-toggle').addEventListener('click',toggleAudio);$('#keyboard-toggle').addEventListener('click',()=>$('#keyboard-panel').classList.toggle('hidden'));$('#keyboard-close').addEventListener('click',()=>$('#keyboard-panel').classList.add('hidden'));$('#send-text').addEventListener('click',()=>{const text=$('#remote-text').value;if(text){sendMessage({type:'text',text});$('#remote-text').value='';toast('文字入力を送信しました')}});$('#remote-text').addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();$('#send-text').click()}});
  async function setWakeLock(){if(!$('#keep-awake').checked||!activePc||!('wakeLock' in navigator)){if(wakeLock){wakeLock.release().catch(()=>{});wakeLock=null}return}try{wakeLock=await navigator.wakeLock.request('screen');wakeLock.addEventListener('release',()=>{wakeLock=null})}catch{toast('このブラウザでは画面スリープ防止を利用できません')}}
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')setWakeLock()});
  async function toggleFullscreen(){try{if(!document.fullscreenElement)await $('#viewer-screen').requestFullscreen();else await document.exitFullscreen()}catch{toast('全画面表示はブラウザの設定により使えない場合があります')}}
  async function hideToolbar(){const view=$('#viewer-screen');view.classList.add('toolbar-hidden');try{if(!document.fullscreenElement)await view.requestFullscreen()}catch{toast('全画面表示はブラウザ設定により利用できません')}}
  function showToolbar(){const view=$('#viewer-screen');view.classList.remove('toolbar-hidden');if(document.fullscreenElement)document.exitFullscreen().catch(()=>{})}
  document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement)$('#viewer-screen').classList.remove('toolbar-hidden')});
  function applyAppDpi(){$('html').style.setProperty('--app-dpi',String(Number($('#app-dpi').value)/100))}
  async function toggleAudio(){if(!dataConn?.open){toast('Windows PCに接続してください');return}if(audioEnabled){sendMessage({type:'audio',enabled:false});setAudioState(false);return}try{audioContext=audioContext||new (window.AudioContext||window.webkitAudioContext)();await audioContext.resume();audioNextTime=audioContext.currentTime;sendMessage({type:'audio',enabled:true});setAudioState(true);toast('Windows音声をEchoで再生します')}catch{setAudioState(false);toast('このブラウザで音声再生を開始できません')}}
  function setAudioState(enabled,message=''){audioEnabled=enabled;const button=$('#audio-toggle');if(button){button.setAttribute('aria-pressed',String(enabled));button.title=enabled?'Windows音声を停止':'Windows音声をEchoから再生'}if(!enabled){for(const source of audioSources){try{source.stop()}catch{}}audioSources.clear();audioNextTime=audioContext?.currentTime||0}if(message)toast(message)}
  function playAudioChunk(packet){if(!audioEnabled||!audioContext||!packet.data)return;try{const raw=base64ToBytes(packet.data),channels=Math.max(1,Math.min(2,packet.channels|0)),frames=Math.floor(raw.length/2/channels);if(!frames)return;const buffer=audioContext.createBuffer(channels,frames,packet.sampleRate||48000),view=new DataView(raw.buffer,raw.byteOffset,raw.byteLength);for(let ch=0;ch<channels;ch++){const out=buffer.getChannelData(ch);for(let i=0;i<frames;i++)out[i]=view.getInt16((i*channels+ch)*2,true)/32768}const source=audioContext.createBufferSource();source.buffer=buffer;source.connect(audioContext.destination);audioSources.add(source);source.onended=()=>audioSources.delete(source);const when=Math.max(audioContext.currentTime+.02,audioNextTime);source.start(when);audioNextTime=when+buffer.duration}catch{}}
  $('#preview-close').addEventListener('click',()=>$('#file-preview').close());$('#file-preview').addEventListener('close',()=>{const url=$('#file-preview').dataset.url;if(url)URL.revokeObjectURL(url);$('#preview-body').replaceChildren()});
  bindVideoInput();renderPcs();initPeer();
})();
